---

sudo: false
dist: bionic
language: ruby
cache: bundler

before_install:
  - sudo add-apt-repository ppa:alex-p/tesseract-ocr -y
  - sudo apt-get update -q
  - sudo apt-get install tesseract-ocr tesseract-ocr-eng ghostscript -y
  - gem install bundler

rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
